CREATE TABLE title_details (
    id BIGSERIAL PRIMARY KEY,
    external_id BIGINT NOT NULL UNIQUE,
    title VARCHAR(500),
    original_title VARCHAR(500),
    plot_overview TEXT,
    type VARCHAR(50),
    runtime_minutes INTEGER,
    year INTEGER,
    end_year INTEGER,
    release_date VARCHAR(50),
    imdb_id VARCHAR(50),
    tmdb_id INTEGER,
    tmdb_type VARCHAR(50),
    genres TEXT,
    genre_names TEXT,
    user_rating DOUBLE PRECISION,
    critic_score INTEGER,
    us_rating VARCHAR(10),
    poster VARCHAR(500),
    backdrop VARCHAR(500),
    original_language VARCHAR(10),
    similar_titles TEXT,
    networks TEXT,
    network_names TEXT,
    trailer VARCHAR(500),
    trailer_thumbnail VARCHAR(500),
    relevance_percentile DOUBLE PRECISION
);
